FROM nvidia/cuda:13.0.2-cudnn-devel-ubi9 AS builder

RUN dnf install -y git
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup update nightly && rustup default nightly

WORKDIR /hanzo
COPY . .

# Rayon threads are limited to minimize memory requirements in CI, avoiding OOM
# Rust threads are increased with a nightly feature for faster compilation (single-threaded by default)
ARG CUDA_COMPUTE_CAP=80
ARG RAYON_NUM_THREADS=4
ARG RUST_NUM_THREADS=4
ARG RUSTFLAGS="-Z threads=${RUST_NUM_THREADS}"
ARG WITH_FEATURES="cuda,cudnn"
RUN cargo build --release --workspace --exclude hanzo-pyo3 --features "${WITH_FEATURES}"

# Stage 2: Minimal runtime environment
FROM nvidia/cuda:13.0.2-cudnn-runtime-ubi9

COPY --chmod=755 --from=builder /hanzo/target/release/hanzo-bench /usr/local/bin/hanzo-bench
COPY --chmod=755 --from=builder /hanzo/target/release/hanzo-server /usr/local/bin/hanzo-server
# Copy chat templates for users running models which may not include them
COPY --from=builder /hanzo/chat_templates /chat_templates

ENV HUGGINGFACE_HUB_CACHE=/data PORT=1234
