//! Virtual try-on: `POST /v1/images/tryon`.
//!
//! Given a person image and a garment image (plus a garment category), returns a photorealistic
//! image of the person wearing the garment, generated by FASHN VTON v1.5 (pixel-space MMDiT). Like
//! image-to-3D, the conditioning is images, so this is a dedicated route rather than the text-prompt
//! image-generation path. The model self-loads (and caches) from HuggingFace on first use.
//!
//! Pose maps (`person_pose` / `garment_pose`) are optional grayscale skeletons; the DWPose detector
//! that derives them is not yet ported, so when omitted a blank pose is used (person quality
//! degrades - see the engine `vton` module docs). Runs segmentation-free (maskless).

use std::time::{SystemTime, UNIX_EPOCH};

use axum::{extract::Json, http::StatusCode, response::IntoResponse};
use base64::{engine::general_purpose::STANDARD, Engine};
use hanzo_engine::diffusion_models::vton::{
    vton_generate, Category, SampleParams, TryOnInputs, DEFAULT_MODEL_ID,
};
use hanzo_ml::Device;
use image::{DynamicImage, ImageFormat};
use serde::{Deserialize, Serialize};

use crate::types::ExtractedState;
use crate::video::fetch_bytes;

const DEFAULT_TIMESTEPS: usize = 30;
const DEFAULT_GUIDANCE: f64 = 1.5;
const DEFAULT_NUM_SAMPLES: usize = 1;
const MAX_TIMESTEPS: usize = 100;
const MAX_NUM_SAMPLES: usize = 4;
const MAX_GUIDANCE: f64 = 30.0;

fn default_model() -> String {
    DEFAULT_MODEL_ID.to_string()
}
fn default_timesteps() -> usize {
    DEFAULT_TIMESTEPS
}
fn default_guidance() -> f64 {
    DEFAULT_GUIDANCE
}
fn default_num_samples() -> usize {
    DEFAULT_NUM_SAMPLES
}
fn default_category() -> String {
    "tops".to_string()
}

/// A virtual try-on request. Image fields accept an http(s) URL, a `data:` URL, an absolute file
/// path, or raw base64.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct TryOnRequest {
    pub person: String,
    pub garment: String,
    #[serde(default = "default_category")]
    pub category: String,
    #[serde(default)]
    pub person_pose: Option<String>,
    #[serde(default)]
    pub garment_pose: Option<String>,
    #[serde(default = "default_model")]
    pub model: String,
    #[serde(default = "default_num_samples")]
    pub num_samples: usize,
    #[serde(default = "default_timesteps")]
    pub num_timesteps: usize,
    #[serde(default = "default_guidance")]
    pub guidance_scale: f64,
    #[serde(default)]
    pub seed: u64,
}

#[derive(Debug, Clone, Serialize)]
pub struct TryOnImage {
    pub b64_json: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct TryOnResponse {
    pub created: u64,
    pub data: Vec<TryOnImage>,
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Try-on runs on CPU by default; set `VTON_DEVICE=cuda:N` to use a GPU (the model loads through the
/// same device path). CPU is the safe default so try-on never contends with a served GPU model.
fn resolve_device() -> anyhow::Result<Device> {
    match std::env::var("VTON_DEVICE") {
        Ok(v) if v.starts_with("cuda") => {
            let ord = v
                .strip_prefix("cuda:")
                .and_then(|s| s.parse().ok())
                .unwrap_or(0);
            Ok(Device::new_cuda(ord)?)
        }
        _ => Ok(Device::Cpu),
    }
}

async fn decode_image(src: &str) -> anyhow::Result<DynamicImage> {
    let bytes = match fetch_bytes(src).await {
        Ok(b) => b,
        Err(_) => STANDARD.decode(src.trim())?,
    };
    Ok(image::load_from_memory(&bytes)?)
}

fn encode_png(img: &DynamicImage) -> anyhow::Result<String> {
    let mut buf = std::io::Cursor::new(Vec::new());
    img.write_to(&mut buf, ImageFormat::Png)?;
    Ok(STANDARD.encode(buf.into_inner()))
}

async fn resolve_inputs(req: &TryOnRequest) -> anyhow::Result<TryOnInputs> {
    let person = decode_image(&req.person).await?;
    let garment = decode_image(&req.garment).await?;
    let person_pose = match &req.person_pose {
        Some(s) => Some(decode_image(s).await?),
        None => None,
    };
    let garment_pose = match &req.garment_pose {
        Some(s) => Some(decode_image(s).await?),
        None => None,
    };
    Ok(TryOnInputs {
        model_id: req.model.clone(),
        person,
        garment,
        person_pose,
        garment_pose,
        category: req.category.parse::<Category>()?,
        num_samples: req.num_samples.clamp(1, MAX_NUM_SAMPLES),
        seed: req.seed,
        sample: SampleParams {
            num_timesteps: req.num_timesteps.clamp(1, MAX_TIMESTEPS),
            guidance_scale: req.guidance_scale.clamp(0.0, MAX_GUIDANCE),
            ..SampleParams::default()
        },
    })
}

/// `POST /v1/images/tryon` - synchronous virtual try-on, returns base64 PNG(s).
pub async fn tryon_generation(
    _state: ExtractedState,
    Json(req): Json<TryOnRequest>,
) -> axum::response::Response {
    let inputs = match resolve_inputs(&req).await {
        Ok(i) => i,
        Err(e) => return bad_request(&e),
    };

    let result = tokio::task::spawn_blocking(move || {
        let device = resolve_device()?;
        vton_generate(&inputs, &device)
    })
    .await;

    match result {
        Ok(Ok(images)) => {
            let data: anyhow::Result<Vec<TryOnImage>> = images
                .iter()
                .map(|img| encode_png(img).map(|b64_json| TryOnImage { b64_json }))
                .collect();
            match data {
                Ok(data) => (
                    StatusCode::OK,
                    Json(TryOnResponse {
                        created: now_unix(),
                        data,
                    }),
                )
                    .into_response(),
                Err(e) => internal_error(&e),
            }
        }
        Ok(Err(e)) => internal_error(&e),
        Err(e) => internal_error(&anyhow::Error::new(e)),
    }
}

fn bad_request(e: &anyhow::Error) -> axum::response::Response {
    (
        StatusCode::UNPROCESSABLE_ENTITY,
        Json(serde_json::json!({ "message": crate::util::sanitize_error_message(e.as_ref()) })),
    )
        .into_response()
}

fn internal_error(e: &anyhow::Error) -> axum::response::Response {
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        Json(serde_json::json!({ "message": crate::util::sanitize_error_message(e.as_ref()) })),
    )
        .into_response()
}
