[package]
name = "hanzo-server"
publish = false
readme = "../README.md"
authors = ["Hanzo AI"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["tokio"] }
clap.workspace = true
ctrlc.workspace = true
directories.workspace = true
either.workspace = true
indexmap.workspace = true
hanzo-engine.workspace = true
hanzo-http.workspace = true
regex.workspace = true
rustyline.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
rust-mcp-sdk.workspace = true
async-trait.workspace = true

[features]
cuda = ["hanzo-engine/cuda", "hanzo-http/cuda"]
vulkan = ["hanzo-engine/vulkan", "hanzo-http/vulkan"]
rocm = ["hanzo-engine/rocm", "hanzo-http/rocm"]
cudnn = ["hanzo-engine/cudnn", "hanzo-http/cudnn"]
metal = ["hanzo-engine/metal", "hanzo-http/metal"]
flash-attn = [
  "cuda",
  "hanzo-engine/flash-attn",
  "hanzo-http/flash-attn",
]
flash-attn-v3 = [
  "cuda",
  "hanzo-engine/flash-attn-v3",
  "hanzo-http/flash-attn-v3",
]
accelerate = ["hanzo-engine/accelerate", "hanzo-http/accelerate"]
mkl = ["hanzo-engine/mkl", "hanzo-http/mkl"]
nccl = ["hanzo-engine/nccl", "hanzo-http/nccl"]
ring = ["hanzo-engine/ring", "hanzo-http/ring"]
mcp-server = ["rust-mcp-sdk/server", "rust-mcp-sdk/hyper-server"]
