#!/usr/bin/env bash
# assemble_paper.sh PAPER_DIR RUN_DIR [RUN_DIR ...]
#
# Fold per-backend harness outputs into the paper's numbers-as-data seam:
#   results-data.tex  = the \renewcommand macros from every run dir (one set per
#                       backend/phase; backends never collide)
#   results-board.tex = one complete booktabs tabular of all rows, \input at float
#                       level by the paper (never rows into an open alignment)
# The paper is then a pure function of the committed run dirs. Idempotent.
set -euo pipefail
PAPER="$1"; shift
[ -d "$PAPER" ] || { echo "no paper dir: $PAPER" >&2; exit 2; }
DATA="$PAPER/results-data.tex"; BOARD="$PAPER/results-board.tex"

echo "% GENERATED by scripts/assemble_paper.sh -- do not hand-edit." > "$DATA"
for d in "$@"; do
  [ -f "$d/results-data.tex" ] && grep '^\\renewcommand' "$d/results-data.tex" >> "$DATA" || true
done

{
  echo "\\begin{tabular}{@{}llrrrrl@{}}"
  echo "\\toprule"
  echo "backend & phase & \$n\$ & hanzo t/s & llama t/s & ratio & verdict \\\\"
  echo "\\midrule"
  for d in "$@"; do [ -f "$d/rows.tex" ] && cat "$d/rows.tex" || true; done
  echo "\\bottomrule"
  echo "\\end{tabular}"
} > "$BOARD"
echo "wrote $DATA ($(grep -c renewcommand "$DATA") macros) and $BOARD ($(grep -c '\\\\\\\\' "$BOARD") rows)"
